import type { MetadataRoute } from "next";

// PWA web manifest. Next.js App Router serves this at /manifest.webmanifest and
// auto-links it from every page <head>. Icons are the lilac-framed AURORA badge
// generated by scripts/generate-icons.mjs.
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "AURORA Shop",
    short_name: "AURORA",
    description:
      "Comprás hoy. Vendés esta semana. Colecciones mayoristas de accesorios con alta rotación.",
    start_url: "/",
    display: "standalone",
    background_color: "#f2e6f7",
    theme_color: "#f2e6f7",
    icons: [
      {
        src: "/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
