[agent]
  interval = "15s"
  round_interval = true
  flush_interval = "15s"
  omit_hostname = false

[[inputs.docker]]
  endpoint = "unix:///var/run/docker.sock"
  gather_services = false
  timeout = "5s"

[[outputs.prometheus_client]]
  listen = ":9273"
  path = "/metrics"
  metric_version = 2
  expiration_interval = "60s"
