name: Deploy to RPI on push to main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, erp] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Pull latest changes on RPI
        run: |
          cd /home/akwiek/code/ERP
          git reset --hard
          git pull
          ./scripts/compose-up.sh
          echo "Repositorio actualizado en la RPI ✅"
